---
title: "project 2"
output: html_notebook
---
```{r}
library(quantmod)
library(PerformanceAnalytics)
library(zoo)
library(ggplot2)
require(TTR)
library(scales)
library(MASS)
library(reshape2)
library(cluster)
library(stats)
library(boot)
library(XML)
library(timeSeries)
```

```{r}
nasdaq_list = read.csv("companylist.nasdaq.csv")
nasdaq_list = na.omit(nasdaq_list[as.numeric(as.character(nasdaq_list[,6])) < 2000,])
nasdaq_list = na.omit(nasdaq_list[as.numeric(as.character(nasdaq_list[,4])) > 10^8,])
nasdaq_tick = as.character(nasdaq_list[,1])
```

```{r }
# Actual loop save stock in new environment
library(quantmod)
stock <- new.env()
n <- length(nasdaq_tick)
pb <- txtProgressBar(min = 0, max = n, style=3)
beg = as.Date("2010-01-01")
end = as.Date("2018-05-04")
for(i in 1:length(nasdaq_tick)) {
  symbol <- nasdaq_tick[i]
  # give up and start the next download if an entry is not available
  tryit <- try(getSymbols(symbol, env = stock, from=beg, to=end, src='yahoo'))
  if(!(inherits(tryit, "try-error") | symbol %in% ls(stock))){
    getSymbols(symbol, env = stock, from=beg, to=end, src='yahoo')
    rm(symbol)
  }
  setTxtProgressBar(pb, i)
}

#put all timeseries in one dataframe
dataset=xts()
nasdaq.names=c()
#Since AMZN has complete data, use it's length as benchmark
len=length(stock$AMZN[,6])
for(i in 1:length(ls(stock))) {
  data=Ad(get(envir = stock,ls(stock)[i]))
  #only put data in dataframe if it has complete entries
  if (length(data)==len){
  dataset <- merge(dataset, data)
  nasdaq.names=c(nasdaq.names,ls(stock)[i])
  }
  rm(data)
}
colnames(dataset) = nasdaq.names

#calculate daily returns
return.data = CalculateReturns(dataset)
#omit missing data
return.data=na.omit(return.data)

save(stock,file="stock.RData")
save(dataset,file="dataset.RData")
save(return.data,file="return.data.RData")
```

```{r}
beg = as.Date("2010-01-01")
end = as.Date("2018-05-04")
getSymbols("^IRX", from=beg, to=end, src='yahoo')
rf = IRX[,6]
```

```{r}
load("stock.RData")
load("dataset.RData")
load("return.data.RData")
```

```{r}
#simple momentum strategy

```

```{r}


Return.portfolio(return.data['2011-01/2012-01',1:5],rebalance_on = "months")

to.weekly(return.data['2011-01/2011-03',1:5],OHLC = FALSE)

```

```{r}
library(quantmod)
beg = as.Date("2010-01-01")
end = as.Date("2018-05-04")
getSymbols("^GSPC", from=beg, to=end, src='yahoo')
sp500 = GSPC[,6]

plot(sp500)
sp500.month = to.weekly(sp500)[,4]

plot(sp500.month)

acf(sp500.month)
acf(na.omit(CalculateReturns(sp500.month)))
```

```{r simple momentum}
library(FinancialInstrument)
library(TTR)
library(PerformanceAnalytics)

RankRB <- function(x){
  # Computes the rank of an xts object of ranking factors
  # ranking factors are the factors that are ranked (i.e. asset returns)
  #
  # args:
  #   x = xts object of ranking factors
  #
  # Returns:
  #   Returns an xts object with ranks
  #   (e.g. for ranking asset returns, the asset with the greatest return
  #    receives a  rank of 1)

  r <- as.xts(t(apply(-x, 1, rank, na.last = "keep")))
  return(r)
}

MonthlyAd <- function(x){
  # Converts daily data to monthly and returns only the monthly close 
  # Note: only used with Yahoo Finance data so far
  # Thanks to Joshua Ulrich for the Monthly Ad function
  # 
  # args:
  #   x = daily price data from Yahoo Finance
  #
  # Returns:
  #   xts object with the monthly adjusted close prices

  sym <- sub("\\..*$", "", names(x)[1])
  Ad(to.monthly(x, indexAt = 'lastof', drop.time = TRUE, name = sym))
}

CAGR <- function(x, m){
  # Function to compute the CAGR given simple returns
  #
  # args:
  #  x = xts of simple returns
  #  m = periods per year (i.e. monthly = 12, daily = 252)
  #
  # Returns the Compound Annual Growth Rate
  x <- na.omit(x)
  cagr <- apply(x, 2, function(x, m) prod(1 + x)^(1 / (length(x) / m)) - 1, m = m)
  return(cagr)
}

SimpleMomentumTest <- function(xts.ret, xts.rank, n = 1, ret.fill.na = 3){
  # returns a list containing a matrix of individual asset returns
  # and the comnbined returns
  # args:
  #  xts.ret = xts of one period returns
  #  xts.rank = xts of ranks
  #  n = number of top ranked assets to trade
  #  ret.fill.na = number of return periods to fill with NA
  #
  # Returns:
  #  returns an xts object of simple returns

  # trade the top n asset(s)
  # if the rank of last period is less than or equal to n,
  # then I would experience the return for this month.

  # lag the rank object by one period to avoid look ahead bias
  lag.rank <- lag(xts.rank, k = 1, na.pad = TRUE)
  n2 <- nrow(lag.rank[is.na(lag.rank[,1]) == TRUE])
  z <- max(n2, ret.fill.na)

  # for trading the top ranked asset, replace all ranks above n
  # with NA to set up for element wise multiplication to get
  # the realized returns
  lag.rank <- as.matrix(lag.rank)
  lag.rank[lag.rank > n] <- NA
  # set the element to 1 for assets ranked <= to rank
  lag.rank[lag.rank <= n] <- 1

  # element wise multiplication of the
  # 1 period return matrix and lagged rank matrix
  mat.ret <- as.matrix(xts.ret) * lag.rank

  # average the rows of the mat.ret to get the
  # return for that period
  vec.ret <- rowMeans(mat.ret, na.rm = TRUE)
  vec.ret[1:z] <- NA

  # convert to an xts object
  vec.ret <- xts(x = vec.ret, order.by = index(xts.ret))
  f <- list(mat = mat.ret, ret = vec.ret, rank = lag.rank)
  return(f)
}
```








```{r momentum backtest}
currency("USD")
#symbols <- c("XLY", "XLP", "XLE", "XLF", "XLV", "XLI", "XLK", "XLB", "XLU", "EFA")#, "TLT", "IEF", "SHY")
largecaptech_list = read.csv("largecaptech.csv")
symbols = as.character(largecaptech_list$Symbol)

stock(symbols, currency = "USD", multiplier = 1)

# create new environment to store symbols
symEnv <- new.env()

# getSymbols and assign the symbols to the symEnv environment
getSymbols(symbols, from = '2010-01-01', to = '2018-05-01', env = symEnv)

# xts object of the monthly adjusted close prices
symbols.close <- do.call(merge, eapply(symEnv, MonthlyAd))

# monthly returns
monthly.returns <- ROC(x = symbols.close, n = 1, type = "discrete", na.pad = TRUE)

#############################################################################
# rate of change and rank based on a single period for 3, 6, 9, and 12 months
#############################################################################

roc.three <- ROC(x = symbols.close , n = 3, type = "discrete")
rank.three <- RankRB(roc.three)

roc.six <- ROC(x = symbols.close , n = 6, type = "discrete")
rank.six <- RankRB(roc.six)

roc.nine <- ROC(x = symbols.close , n = 9, type = "discrete")
rank.nine <- RankRB(roc.nine)

roc.twelve <- ROC(x = symbols.close , n = 12, type = "discrete")
rank.twelve <- RankRB(roc.twelve)

num.assets <- 6

# simple momentum test based on 3 month ROC to rank
case1 <- SimpleMomentumTest(xts.ret = monthly.returns, xts.rank = rank.three,
                            n = num.assets, ret.fill.na = 15)

# simple momentum test based on 6 month ROC to rank
case2 <- SimpleMomentumTest(xts.ret = monthly.returns, xts.rank = rank.six,
                            n = num.assets, ret.fill.na = 15)

# simple momentum test based on 9 month ROC to rank
case3 <- SimpleMomentumTest(xts.ret = monthly.returns, xts.rank = rank.nine,
                            n = num.assets, ret.fill.na = 15)

# simple momentum test based on 12 month ROC to rank
case4 <- SimpleMomentumTest(xts.ret = monthly.returns, xts.rank = rank.twelve,
                            n = num.assets, ret.fill.na = 15)

returns <- cbind(case1$ret, case2$ret, case3$ret, case4$ret)
colnames(returns) <- c("3-Month", "6-Month", "9-Month", "12-Month")

charts.PerformanceSummary(R = returns, Rf = 0, geometric = TRUE, 
                          main = "Momentum Cumulative Return: Top 6 Assets")

table.Stats(returns)

CAGR(returns, m = 12)

print("End")
```

```{r}
png(filename="simplemomentum.png")
charts.PerformanceSummary(R = returns, Rf = 0, geometric = TRUE, 
                          main = "Momentum Cumulative Return: Top 6 Assets")
dev.off()

acf(na.omit(returns$`3-Month`))
```

```{r}
library('R.matlab')
tsdata = readMat('tsdata.mat')
```

